CONTEXT_FILEPATH = "text/context.md"

EVERGREEN_PROGRAM_NAME = "Evergreen Fund"
FILM_TAX_CREDIT_PROGRAM = "Film Tax Credit Program"
DIGITAL_MEDIA_TAX_CREDIT_PROGRAM = "Digital Media Tax Credit Program"
TECH_BIOTECH_NOL_PROGRAM = "Technology Business Tax Certificate Transfer (NOL) Program"
NJ_RISE_PROGRAM = "NJ Rise Program"
ASPIRE_PROGRAM = "ASPIRE Program"
EMERGE_PROGRAM = "EMERGE Program"
BROWNFIELD_PROGRAM = "Brownfield Redevelopment Program"
OFFSHORE_WIND_PROGRAM = "Offshore Wind Tax Credit Program"